-- INSERT INSURANCE COMPANIES
INSERT INTO INSURANCE_COMPANIES (NAME)
VALUES ('ETHIAS'), ('ARGENTA');

-- INSERT INSURANCE AGENCIES
INSERT INTO INSURANCE_AGENCIES (NAME, ADDRESS, COUNTRY, PHONENUMBER, EMAIL)
VALUES ('ARCES', 'DESGUINLEI 92, 2018 ANTWERPEN', 'BE', '032591970', 'INFO@ARCES.BE'),
       ('ING', 'RINGLAAN 92, 2027 ANTWERPEN', 'BE', '032598950', 'INFO@ING.BE');

-- INSERT MOTORS
INSERT INTO VEHICLES (VEHICLE_TYPE, MARKTYPE, LICENSEPLATE, COUNTRYOFREGISTRATION)
VALUES ('MOTOR', 'VOLKSWAGEN', '6JIO87', 'BELGIUM');

-- INSERT TRAILERS
INSERT INTO VEHICLES (VEHICLE_TYPE, HASREGISTRATION, LICENSEPLATE, COUNTRYOFREGISTRATION)
VALUES ('TRAILER', TRUE, '5HU489', 'BELGIUM');

INSERT INTO INSURANCE_CERTIFICATES (POLICYNUMBER, GREENCARDNUMBER, AVAILABILITYDATE, EXPIRATIONDATE, INSURANCE_COMPANY_ID, INSURANCE_AGENCY_ID, MATERIALDAMAGECOVERED, VEHICLE_ID)
VALUES ('POL123456789', 'GCN987654321', CURRENT_DATE, '2025-02-28', (SELECT ID FROM INSURANCE_COMPANIES WHERE NAME = 'ETHIAS'), (SELECT ID FROM INSURANCE_AGENCIES WHERE NAME = 'ARCES'), TRUE, (SELECT ID FROM VEHICLES WHERE LICENSEPLATE = '6JIO87')),
       ('POL987654321', 'GCN123456789', CURRENT_DATE, '2025-02-28', (SELECT ID FROM INSURANCE_COMPANIES WHERE NAME = 'ARGENTA'), (SELECT ID FROM INSURANCE_AGENCIES WHERE NAME = 'ING'), FALSE, (SELECT ID FROM VEHICLES WHERE LICENSEPLATE = '5HU489'));

-- INSERT USER PART
INSERT INTO USERS (EMAIL, PASSWORD, ROLE, RESETCODE)
VALUES ('johndoe@gmail.com', 'Example_123', 'POLICY_HOLDER', '123456');

-- INSERT POLICYHOLDER PART
INSERT INTO POLICY_HOLDERS (FIRSTNAME, LASTNAME, ADDRESS, POSTALCODE, PHONENUMBER)
VALUES ('JOHN', 'DOE', 'KONINGIN ASTRIDPLEIN 27, 2018 ANTWERPEN', '2018', '0465879425');
