DROP TABLE IF EXISTS ACCIDENT_IMAGES CASCADE;
DROP TABLE IF EXISTS ACCIDENT_STATEMENTS CASCADE;
DROP TABLE IF EXISTS ACCIDENT_STATEMENTS_DRIVERS CASCADE;
DROP TABLE IF EXISTS ACCIDENT_STATEMENTS_POLICY_HOLDERS CASCADE;
DROP TABLE IF EXISTS ACCIDENT_STATEMENTS_UNREGISTERED_TRAILERS CASCADE;
DROP TABLE IF EXISTS ACCIDENT_STATEMENTS_VEHICLEAACCIDENT_IMAGES CASCADE;
DROP TABLE IF EXISTS ACCIDENT_STATEMENTS_VEHICLEBACCIDENT_IMAGES CASCADE;
DROP TABLE IF EXISTS ACCIDENT_STATEMENT_VEHICLEACIRCUMSTANCES CASCADE;
DROP TABLE IF EXISTS ACCIDENT_STATEMENT_VEHICLEBCIRCUMSTANCES CASCADE;
DROP TABLE IF EXISTS DRIVERS CASCADE;
DROP TABLE IF EXISTS INSURANCE_AGENCIES CASCADE;
DROP TABLE IF EXISTS INSURANCE_COMPANIES CASCADE;
DROP TABLE IF EXISTS POLICY_HOLDERS_INSURANCE_CERTIFICATES CASCADE;
DROP TABLE IF EXISTS INSURANCE_CERTIFICATES CASCADE;
DROP TABLE IF EXISTS POLICY_HOLDERS CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS VEHICLES CASCADE;
DROP TABLE IF EXISTS WITNESES CASCADE;

DROP SEQUENCE IF EXISTS ACCIDENT_IMAGES_SEQ;
DROP SEQUENCE IF EXISTS ACCIDENT_STATEMENTS_SEQ;
DROP SEQUENCE IF EXISTS DRIVERS_SEQ;
DROP SEQUENCE IF EXISTS INSURANCE_AGENCIES_SEQ;
DROP SEQUENCE IF EXISTS INSURANCE_CERTIFICATES_SEQ;
DROP SEQUENCE IF EXISTS INSURANCE_COMPANIES_SEQ;
DROP SEQUENCE IF EXISTS USERS_SEQ;
DROP SEQUENCE IF EXISTS POLICY_HOLDERS_SEQ;
DROP SEQUENCE IF EXISTS VEHICLES_SEQ;
DROP SEQUENCE IF EXISTS WITNESES_SEQ;

CREATE SEQUENCE ACCIDENT_IMAGES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ACCIDENT_STATEMENTS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DRIVERS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE INSURANCE_AGENCIES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE INSURANCE_CERTIFICATES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE INSURANCE_COMPANIES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE POLICY_HOLDERS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE VEHICLES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE WITNESES_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE ACCIDENT_IMAGES
(
    ID         INT DEFAULT NEXTVAL('ACCIDENT_IMAGES_SEQ') NOT NULL PRIMARY KEY,
    IMAGE_DATA BLOB                                       NULL
);

CREATE TABLE DRIVERS
(
    ID                           INT DEFAULT NEXTVAL('DRIVERS_SEQ') NOT NULL PRIMARY KEY,
    BIRTHDAY                     DATE                               NULL,
    DRIVINGLICENSEEXPIRATIONDATE DATE                               NULL,
    ADDRESS                      VARCHAR(255)                       NULL,
    CATEGORY                     VARCHAR(255)                       NULL,
    COUNTRY                      VARCHAR(255)                       NULL,
    DRIVINGLICENSENR             VARCHAR(255)                       NULL,
    EMAIL                        VARCHAR(255)                       NULL,
    FIRSTNAME                    VARCHAR(255)                       NULL,
    LASTNAME                     VARCHAR(255)                       NULL,
    PHONENUMBER                  VARCHAR(255)                       NULL
);

CREATE TABLE INSURANCE_AGENCIES
(
    ID          INT DEFAULT NEXTVAL('INSURANCE_AGENCIES_SEQ') NOT NULL PRIMARY KEY,
    ADDRESS     VARCHAR(255)                                  NULL,
    COUNTRY     VARCHAR(255)                                  NULL,
    EMAIL       VARCHAR(255)                                  NULL,
    NAME        VARCHAR(255)                                  NULL,
    PHONENUMBER VARCHAR(255)                                  NULL
);

CREATE TABLE INSURANCE_COMPANIES
(
    ID   INT DEFAULT NEXTVAL('INSURANCE_COMPANIES_SEQ') NOT NULL PRIMARY KEY,
    NAME VARCHAR(255)                                   NULL
);

CREATE TABLE USERS
(
    ID        INT DEFAULT NEXTVAL('USERS_SEQ') NOT NULL PRIMARY KEY,
    EMAIL     VARCHAR(255)                     NULL,
    PASSWORD  VARCHAR(255)                     NULL,
    RESETCODE VARCHAR(255)                     NULL,
    ROLE      ENUM ('POLICY_HOLDER')           NULL
);

CREATE TABLE POLICY_HOLDERS
(
    ID          INT DEFAULT NEXTVAL('POLICY_HOLDERS_SEQ') NOT NULL PRIMARY KEY, -- USE A SEPARATE SEQUENCE FOR POLICY_HOLDERS
    ADDRESS     VARCHAR(255)                              NULL,
    FIRSTNAME   VARCHAR(255)                              NULL,
    LASTNAME    VARCHAR(255)                              NULL,
    PHONENUMBER VARCHAR(255)                              NULL,
    POSTALCODE  VARCHAR(255)                              NULL
);

CREATE TABLE VEHICLES
(
    ID                    INT DEFAULT NEXTVAL('VEHICLES_SEQ') NOT NULL PRIMARY KEY,
    HASREGISTRATION       BIT                                 NULL,
    VEHICLE_TYPE          VARCHAR(31)                         NOT NULL,
    COUNTRYOFREGISTRATION VARCHAR(255)                        NULL,
    LICENSEPLATE          VARCHAR(255)                        NULL,
    MARKTYPE              VARCHAR(255)                        NULL,
    OFVEHICLE             VARCHAR(255)                        NULL
);

CREATE TABLE INSURANCE_CERTIFICATES
(
    ID                    INT DEFAULT NEXTVAL('INSURANCE_CERTIFICATES_SEQ') NOT NULL PRIMARY KEY,
    AVAILABILITYDATE      DATE                                              NULL,
    EXPIRATIONDATE        DATE                                              NULL,
    INSURANCE_AGENCY_ID   INT                                               NULL,
    INSURANCE_COMPANY_ID  INT                                               NULL,
    MATERIALDAMAGECOVERED BIT                                               NULL,
    VEHICLE_ID            INT                                               NULL,
    GREENCARDNUMBER       VARCHAR(255)                                      NULL,
    POLICYNUMBER          VARCHAR(255)                                      NULL
);

CREATE TABLE WITNESES
(
    ID          INT DEFAULT NEXTVAL('WITNESES_SEQ') NOT NULL PRIMARY KEY,
    ADDRESS     VARCHAR(255)                        NULL,
    NAME        VARCHAR(255)                        NULL,
    PHONENUMBER VARCHAR(255)                        NULL
);

CREATE TABLE ACCIDENT_STATEMENTS
(
    ID                               INT DEFAULT NEXTVAL('ACCIDENT_STATEMENTS_SEQ') NOT NULL PRIMARY KEY,
    DAMAGETOOBJECTS                  BIT                                            NULL,
    DAMAGETOOTHERCARS                BIT                                            NULL,
    INJURED                          BIT                                            NULL,
    NUMBEROFCIRCUMSTANCES            INT                                            NULL,
    WITNESS_ID                       INT                                            NULL,
    DATE                             TIMESTAMP                                      NULL,
    LOCATION                         VARCHAR(255)                                   NULL,
    VEHICLEAREMARK                   VARCHAR(255)                                   NULL,
    VEHICLEAVISIBLEDAMAGEDESCRIPTION VARCHAR(255)                                   NULL,
    VEHICLEBREMARK                   VARCHAR(255)                                   NULL,
    VEHICLEBVISIBLEDAMAGEDESCRIPTION VARCHAR(255)                                   NULL,
    SKETCHOFACCIDENT                 LONGBLOB                                           NULL,
    VEHICLEAINITIALIMPACTSKETCH      LONGBLOB                                           NULL,
    VEHICLEASIGNATURE                LONGBLOB                                           NULL,
    VEHICLEBINITIALIMPACTSKETCH      LONGBLOB                                           NULL,
    VEHICLEBSIGNATURE                LONGBLOB                                           NULL
);

CREATE TABLE POLICY_HOLDERS_INSURANCE_CERTIFICATES
(
    POLICY_HOLDERS_ID        INT NOT NULL,
    INSURANCECERTIFICATES_ID INT NOT NULL,
    PRIMARY KEY (POLICY_HOLDERS_ID, INSURANCECERTIFICATES_ID),
    FOREIGN KEY (POLICY_HOLDERS_ID) REFERENCES POLICY_HOLDERS (ID),
    FOREIGN KEY (INSURANCECERTIFICATES_ID) REFERENCES INSURANCE_CERTIFICATES (ID)
);

CREATE TABLE ACCIDENT_STATEMENT_VEHICLEACIRCUMSTANCES
(
    ACCIDENT_STATEMENTS_ID INT          NOT NULL,
    VEHICLEACIRCUMSTANCES  VARCHAR(255) NULL
);

CREATE TABLE ACCIDENT_STATEMENT_VEHICLEBCIRCUMSTANCES
(
    ACCIDENT_STATEMENTS_ID INT          NOT NULL,
    VEHICLEBCIRCUMSTANCES  VARCHAR(255) NULL
);

CREATE TABLE ACCIDENT_STATEMENTS_DRIVERS
(
    ACCIDENT_STATEMENTS_ID INT NOT NULL,
    DRIVERS_ID             INT NOT NULL
);

CREATE TABLE ACCIDENT_STATEMENTS_POLICY_HOLDERS
(
    ACCIDENT_STATEMENTS_ID INT NOT NULL,
    POLICYHOLDERS_ID       INT NOT NULL
);

CREATE TABLE ACCIDENT_STATEMENTS_UNREGISTERED_TRAILERS
(
    ACCIDENT_STATEMENTS_ID   INT NOT NULL,
    UNREGISTERED_TRAILERS_ID INT NOT NULL
);

CREATE TABLE ACCIDENT_STATEMENTS_VEHICLEAACCIDENT_IMAGES
(
    ACCIDENT_STATEMENTS_ID    INT NOT NULL,
    VEHICLEAACCIDENTIMAGES_ID INT NOT NULL,
    PRIMARY KEY (ACCIDENT_STATEMENTS_ID, VEHICLEAACCIDENTIMAGES_ID),
    FOREIGN KEY (ACCIDENT_STATEMENTS_ID) REFERENCES ACCIDENT_STATEMENTS(ID),
    FOREIGN KEY (VEHICLEAACCIDENTIMAGES_ID) REFERENCES ACCIDENT_IMAGES(ID)
);

CREATE TABLE ACCIDENT_STATEMENTS_VEHICLEBACCIDENT_IMAGES
(
    ACCIDENT_STATEMENTS_ID    INT NOT NULL,
    VEHICLEBACCIDENTIMAGES_ID INT NOT NULL,
    PRIMARY KEY (ACCIDENT_STATEMENTS_ID, VEHICLEBACCIDENTIMAGES_ID),
    FOREIGN KEY (ACCIDENT_STATEMENTS_ID) REFERENCES ACCIDENT_STATEMENTS(ID),
    FOREIGN KEY (VEHICLEBACCIDENTIMAGES_ID) REFERENCES ACCIDENT_IMAGES(ID)
);


